### PR TITLE
Re-style nav borders to be more like ubuntu.com

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

Re-style nav borders to be more like ubuntu.com

## QA 

Check that the borders on the desktop main nav are similar to the borders on ubuntu.com

### CODE REVIEW

**Comment by anthonydillon** [comment]
@grahambancroft can you add design QA steps please

**Comment by joanasa89** [comment]
Looks good to me! @yaili can you have a look to the demo pls? https://staging.conjure-up.io/#navigation

**Comment by joanasa89** [comment]
External links on the navigation - make hover state style same as ubuntu.com (keeping the external icon)

**Comment by yaili** [comment]
Yes, looks good to me too.

**Comment by yaili** [comment]
I won't add design +1, @joanasa89 you can add it once you're happy about your external link request. Thanks!

**Comment by joanasa89** [comment]
@grahambancroft looks good to me!

**Comment by grahambancroft** [comment]
Hi @joanasa89 the nav is ready for review https://staging.conjure-up.io/

**Pull request merged**
