### PR TITLE
Run script

### PR DESCRIPTION
**Pull request by nottrobin**
Add the standard `run-jekyll` script to conjure-up.io

QA
--

``` bash
./run clean
./run
./run test
etc.
```

### CODE REVIEW

**Comment by nottrobin** [comment]
[Add run script](https://trello.com/c/zDWZhaPn/3293-add-run-script)

**Comment by WillMoggridge** [comment]
I am not entirely sure how I feel changing the build script to stop building the whole site.
It is moving the single build command API to some hidden set up and logic for Jekyll.

Right now, the build server just runs `npm run build` and it builds the whole site ready for deploy. That seems like a great thing to keep.

**Comment by nottrobin** [comment]
@WillMoggridge yes that would be conceptually different from the way I'm thinking about this. I am saying that `yarn`/`npm` is responsible for managing key responsibilities - building CSS and if we needed it JavaScript. And then we have another layer that's responsible for building and serving Jekyll. I understand that in our other apps it is nice to keep the separation between "building" and "serving" the application, but Jekyll already blurs this line, as it is the build agent, the server, and the watcher.

While it would be nice, all other things being equal, to keep all build actions in one place, you're suggesting we run Ruby inside the Node image. This would mean re-architecting the whole way we run Ruby, and throw into question the way we're encapsulating dependencies in general - if we're mixing Ruby and Node then why not Python as well?

I personally think there are many benefits to keeping our dependencies layered in the way we currently are. Especially since we have a number of different sites which work a number of different ways (node+django, node+jekyll, node on its own, django on its own), it's especially useful to keep the different layers apart so we can understand more clearly how they're being run and whether they're likely to have interactions between each other.

I would rather keep it as it is (and also to change it to your way would at this point be a lot of work).

**Comment by WillMoggridge** [comment]
I was not saying or suggesting we should change our whole stack, it just seemed to not match up to our previous work with having the logic visible and the ./run being an optional layer.

For example the sass command is visible in the package.json but the jekyll command is hidden away.

This definitely isn't worth blocking on and I'll happily approve the changes.

**Comment by nottrobin** [comment]
Thanks @WillMoggridge, I created https://github.com/canonical-webteam/generator-canonical-webteam/issues/25 to continue the discussion.

**Pull request merged**
